#!/usr/bin/env perl

use strict;
use warnings;
use 5.012;

use PerlIO::gzip;
use Data::Dumper;

binmode STDIN, ":gzip(auto)";

# parse header
chomp( my $header = <STDIN> );
my @fields = map {
    $_ =~ s/^"//;
    $_ =~ s/"$//;
    $_;
} split "\t", $header;

my %map;
@map{@fields} = (0..$#fields);

my %table;

while (my $line = <STDIN>) {

    chomp $line;
    my @values = split "\t", $line;

}

print Dumper %table;

exit;

